name: Deploy to GitHub pages
on:
  push:
    branches:
      - main
jobs:
  build-jupyter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install the dependencies
        working-directory: ./jupyterlite
        run: |
          python -m pip install -r requirements.txt
      - name: Build the JupyterLite site
        working-directory: ./jupyterlite
        run: |
          cp README.md content
          jupyter lite build --contents content
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      working-directory: ./app
      run: npm install
    - name: Build
      working-directory: ./app
      run: npm run build
    - name: Build app
      working-directory: ./app
      run: npm run predeploy
    - name: Copy JupyterLite
      run: cp -r ./jupyterlite/_output ./app/build/public/jupyterlite
      id: random-color-generator
    - name: Deploy app
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./app/build