name: Deploy to GitHub pages
on:
  push:
    branches:
      - dev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install the dependencies
        working-directory: ./jupyterlite
        run: |
          python -m pip install -r requirements.txt
      - name: Build the JupyterLite site
        working-directory: ./jupyterlite
        run: |
          jupyter lite build --contents content
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        working-directory: ./app
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_READONLY_TOKEN }}
      - name: Build
        working-directory: ./app
        run: yarn build
      - name: Build app
        working-directory: ./app
        run: yarn predeploy
      - name: Copy JupyterLite
        run: cp -r ./jupyterlite/_output ./app/build/public/jupyterlite
      - name: Deploy app
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/build